from typing import Literal

from pydantic import BaseModel, ConfigDict, Field


class SourceReference(BaseModel):
    """Reference to a document chunk used to support an answer."""

    model_config = ConfigDict(extra="forbid")

    document_id: str = Field(
        ...,
        min_length=1,
        max_length=256,
        description="Unique identifier of the source document.",
    )

    title: str = Field(
        ...,
        min_length=1,
        max_length=256,
        description="Human-readable source title.",
    )

    chunk_id: str = Field(
        ...,
        min_length=1,
        max_length=256,
        description="Identifier of the retrieved document chunk.",
    )

    score: float | None = Field(
        default=None,
        ge=0,
        description="Retrieval relevance score when available.",
    )


class QueryMetadata(BaseModel):
    """Operational metadata produced during query processing."""

    model_config = ConfigDict(extra="forbid")

    agents_used: list[str] = Field(
        default_factory=list,
        description="Agents that participated in the execution.",
    )

    retrieval_count: int = Field(
        default=0,
        ge=0,
        description="Number of document chunks retrieved.",
    )

    verification_status: Literal[
        "not_run",
        "passed",
        "needs_more_evidence",
        "failed",
    ] = "not_run"

    duration_ms: float | None = Field(
        default=None,
        ge=0,
        description="Total processing duration in milliseconds.",
    )


class QueryResponse(BaseModel):
    """Response contract returned by SentinelAI."""

    model_config = ConfigDict(
        extra="forbid",
        str_strip_whitespace=True,
    )

    answer: str = Field(
        ...,
        min_length=1,
        description="Final answer generated by SentinelAI.",
    )

    thread_id: str = Field(
        ...,
        min_length=1,
        max_length=128,
        description="Conversation identifier associated with LangGraph state.",
    )

    sources: list[SourceReference] = Field(default_factory=list)

    metadata: QueryMetadata = Field(default_factory=QueryMetadata)

    trace_id: str | None = Field(
        default=None,
        min_length=1,
        max_length=256,
        description="Observability trace identifier when available.",
    )